#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "${API_DB_USER}" WITH PASSWORD '${API_DB_PASSWORD}';

    GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${API_DB_USER}";
    GRANT USAGE ON SCHEMA ML TO "${API_DB_USER}";

    GRANT INSERT , SELECT ON TABLE ML.ModelInferences TO "${API_DB_USER}";
    GRANT USAGE ON SEQUENCE ML.ModelInferences_id_seq TO "${API_DB_USER}";

EOSQL